// Setas (D-pad), paletas dos controles, ícone do perfil e tela final com classificação e prêmio −20%.
const {chromium}=require('playwright-core');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
let bad=0;const ok=(c,m)=>{console.log((c?'OK  ':'FALHOU ')+m);if(!c)bad++};
(async()=>{const b=await chromium.launch(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{});
 const c=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const p=await c.newPage();p.on('pageerror',e=>ok(false,'pageerror '+e.message));
 await p.addInitScript(()=>{window.__bcCount=0;localStorage.setItem('bc_cfg',JSON.stringify({fs:false}))});
 await p.goto('http://127.0.0.1:8765/');await sleep(1200);await p.evaluate(()=>window.__bcEnter());await sleep(700);await p.click('#hello-ok');await sleep(600);
 ok(await p.evaluate(()=>/× a entrada − 20% da banca/.test(document.getElementById('dm-facts').textContent)),'texto do prêmio: −20% da banca');
 await p.evaluate(()=>document.getElementById('cfg-open').click());await sleep(300);
 ok(await p.evaluate(()=>document.querySelectorAll('#c-pals .pal').length)>=10,'10+ paletas de cores dos controles');
 await p.evaluate(()=>{document.querySelector('#c-ptype [data-v=dpad]').click();document.querySelector('#c-pals [data-pal=a_jun]').click()});await sleep(200);
 const cf=await p.evaluate(()=>({c:JSON.parse(localStorage.bc_cfg),dp:document.getElementById('stick').classList.contains('dpad'),bg:getComputedStyle(document.getElementById('console')).getPropertyValue('--jl-bg').slice(0,60)}));
 ok(cf.c.ptype==='dpad'&&cf.c.pal==='a_jun'&&cf.dp,'setas + paleta salvas e aplicadas');ok(/url\(/.test(cf.bg),'paleta de arte usa a textura do mapa');
 await p.evaluate(()=>document.getElementById('cfg').close());
 await p.evaluate(()=>{document.querySelector('#rail .card[data-k="4x4"]').click()});await p.evaluate(()=>window.__bcSolo());
 await p.waitForFunction(()=>window.__arena.active,null,{timeout:8000});await sleep(1200);
 const r=await p.evaluate(()=>{const e=document.querySelector('#stick i.d').getBoundingClientRect();return[e.left+e.width/2,e.top+e.height/2]});
 const y0=await p.evaluate(()=>window.__arena._s().players[0].y);
 await p.evaluate(([x,y])=>document.querySelector('.jl').dispatchEvent(new PointerEvent('pointerdown',{pointerId:3,clientX:x,clientY:y,bubbles:true,pointerType:'touch',isPrimary:true})),r);await sleep(600);
 const y1=await p.evaluate(()=>window.__arena._s().players[0].y);
 await p.evaluate(([x,y])=>document.querySelector('.jl').dispatchEvent(new PointerEvent('pointerup',{pointerId:3,clientX:x,clientY:y,bubbles:true,pointerType:'touch'})),r);
 ok(y1-y0>20,'seta para baixo anda ('+Math.round(y1-y0)+'px)');
 await p.evaluate(async()=>{const ps=window.__arena._s().players;for(let i=ps.length-1;i>=1;i--){ps[i].alive=false;ps[i].deadAt=performance.now();await new Promise(r=>setTimeout(r,60))}});
 await p.waitForFunction(()=>document.getElementById('s-end').classList.contains('on'),null,{timeout:8000});
 const e=await p.evaluate(()=>({rows:[...document.querySelectorAll('#e-rank li')].map(l=>({pos:l.querySelector('.pos').textContent,pz:l.querySelector('.pz b').textContent,av:!!l.querySelector('.av').style.backgroundImage})),sum:document.getElementById('e-sum').innerText}));
 ok(e.rows.length===4,'classificação com os 4 participantes');ok(e.rows.map(r=>r.pos).join()==='1º,2º,3º,4º','posições 1º a 4º');
 ok(e.rows[0].pz==='R$ 16,00'&&e.rows.slice(1).every(r=>r.pz==='R$ 0,00'),'prêmio: R$ 20 − 20% = R$ 16 só para o 1º');ok(e.rows.every(r=>r.av),'cada linha com o boneco');
 ok(/Banca 20%/i.test(e.sum)&&/R\$ 4/.test(e.sum),'resumo mostra banca de 20% (R$ 4)');
 await p.evaluate(()=>document.getElementById('back').click());await sleep(400);await p.evaluate(()=>document.getElementById('me').click());await sleep(300);
 ok(await p.evaluate(()=>document.querySelectorAll('#p-icons button').length)===10,'10 ícones de perfil');
 await p.evaluate(()=>document.querySelector('#p-icons [data-ic=cas]').click());
 ok(await p.evaluate(()=>document.getElementById('me-av').classList.contains('ic-map')&&JSON.parse(localStorage.bc_player).icon==='cas'),'ícone do mapa aplicado e salvo');
 await b.close();console.log(bad?bad+' falha(s)':'tudo certo');process.exit(bad?1:0)})().catch(e=>{console.log('ERRO',e.message);process.exit(1)});
