const {chromium}=require('playwright-core');const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const ok=(c,m)=>{console.log((c?'OK  ':'FALHA ')+m);if(!c)process.exitCode=1};
(async()=>{const b=await chromium.launch(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{});
 const c=await b.newContext({viewport:{width:844,height:390},isMobile:true,hasTouch:true});const p=await c.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
 await p.goto('http://127.0.0.1:8765/');await sleep(1200);
 const st=await p.evaluate(()=>{const i=document.getElementById('intro');return{cls:i.className,logoVisible:getComputedStyle(document.querySelector('#intro .lwrap')).visibility!=='hidden'&&getComputedStyle(document.querySelector('#intro .lwrap')).display!=='none'}});
 ok(st.cls.includes('legacy')&&!st.cls.includes('art'),'sem as imagens: cai na abertura antiga ('+st.cls+')');ok(st.logoVisible,'logo antiga visivel');
 await p.touchscreen.tap(400,200);await sleep(700);ok(await p.evaluate(()=>document.getElementById('intro').classList.contains('msg')),'toque abre o aviso 18+ no modo antigo');
 await p.click('#hello-ok');await sleep(800);ok(await p.evaluate(()=>!document.getElementById('intro')),'entra no lobby');ok(errs.length===0,'sem erros '+errs.join('|'));
 await b.close();process.exit(process.exitCode||0)})();
